services:
  db:
    image:    mysql:8.0
    restart:  always
    volumes:
      - mysql-db:/var/lib/mysql
      - ./docker_config/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      MYSQL_DATABASE:       toremember
      MYSQL_ROOT_PASSWORD:  root
    ports:
      - 3307:3306
    expose:
      - 3307:3306
    healthcheck:
        test:     ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout:  10s
        retries:  10

volumes:
  mysql-db:
    driver: local
